In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import model_selection
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
import pydotplus

In [3]:
iris = datasets.load_iris()

In [6]:
x = iris.data
y = iris.target

In [15]:
x_train,x_test,y_train,y_test = model_selection.train_test_split(x,y,random_state=0)

In [16]:
scaler = preprocessing.StandardScaler()

In [17]:
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [18]:
scaler.transform(x_train)

array([[  1.54399532e-02,  -1.19254753e-01,   2.25126850e-01,
          3.56381749e-01],
       [ -9.98450310e-02,  -1.04039491e+00,   1.13559562e-01,
         -2.86480506e-02],
       [  1.05300481e+00,  -1.19254753e-01,   9.50314227e-01,
          1.12644135e+00],
       [ -1.36797986e+00,   3.41315328e-01,  -1.39259884e+00,
         -1.31208072e+00],
       [  1.16828980e+00,   1.11030287e-01,   7.27179649e-01,
          1.38312788e+00],
       [ -1.02212490e+00,   1.03217045e+00,  -1.22524790e+00,
         -7.98707650e-01],
       [ -5.60984968e-01,   1.49274053e+00,  -1.28103155e+00,
         -1.31208072e+00],
       [ -1.02212490e+00,  -2.42210516e+00,  -1.65358660e-01,
         -2.85334584e-01],
       [  7.07149859e-01,  -1.19254753e-01,   9.50314227e-01,
          7.41411549e-01],
       [  9.37719827e-01,   5.71600368e-01,   1.06188152e+00,
          1.63981441e+00],
       [  1.30724937e-01,  -1.96153508e+00,   6.71396005e-01,
          3.56381749e-01],
       [  9.37719827e

In [20]:
scaler.transform(x_test)

array([[-0.09984503, -0.57982483,  0.72717965,  1.51147115],
       [ 0.13072494, -1.96153508,  0.11355956, -0.28533458],
       [-0.44569998,  2.64416573, -1.33681519, -1.31208072],
       [ 1.62942973, -0.34953979,  1.39658338,  0.74141155],
       [-1.0221249 ,  0.80188541, -1.28103155, -1.31208072],
       [ 0.47657989,  0.57160037,  1.22923245,  1.63981441],
       [-1.0221249 ,  1.03217045, -1.39259884, -1.18373745],
       [ 0.93771983,  0.11103029,  0.50404507,  0.35638175],
       [ 1.05300481, -0.57982483,  0.55982872,  0.22803848],
       [ 0.24600992, -0.57982483,  0.11355956,  0.09969522],
       [ 0.24600992, -1.04039491,  1.00609787,  0.22803848],
       [ 0.59186487,  0.34131533,  0.39247778,  0.35638175],
       [ 0.24600992, -0.57982483,  0.50404507, -0.02864805],
       [ 0.70714986, -0.57982483,  0.44826143,  0.35638175],
       [ 0.24600992, -0.34953979,  0.50404507,  0.22803848],
       [-1.13740989,  0.11103029, -1.28103155, -1.44042398],
       [ 0.13072494, -0.

In [21]:
clf = DecisionTreeClassifier()

In [23]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
print(clf.score(x_test,y_test))
print(clf.score(x_train,y_train))

0.973684210526
1.0


In [29]:
dot_data = export_graphviz(clf,out_file=None,feature_names = iris.feature_names,class_names = iris.target_names,filled=True,rounded=True)

In [30]:
graph = pydotplus.graph_from_dot_data(dot_data)

In [31]:
graph.write_pdf("iris.pdf")

True

In [39]:
from sklearn.metrics import confusion_matrix,classification_report

In [40]:
y_pre = clf.predict(x_test)

In [42]:
y_pre - y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [43]:
confusion_matrix(y_test,y_pre)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [44]:
print(classification_report(y_test,y_pre))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       1.00      0.94      0.97        16
          2       0.90      1.00      0.95         9

avg / total       0.98      0.97      0.97        38

