In [17]:
print(10,end = " ")
print(20)
com = 2+3j #python allows for complex numbers as a type too
type(com)

10 20


complex

In [3]:
a = int(input("Please enter a number:"))
print(a)

Please enter a number:10
10


In [16]:
str = "Hello world"
str[0]
str+=" to this place"

str.lower()
str.upper()
str[1:4]

str1 = " abc def"
str1 = str1.strip()
str2 = str1.split(" ")
str2

['abc', 'def']

In [21]:
##Tuple

tup = ("str",1,("str2",1))
tup[0]

'str'

In [24]:
def sum(a,b,*more):
    print(more[0])
    print(type(more))
    
sum(10,15,20,12,14)

20
<class 'tuple'>


In [43]:
##Lists

l1 = [i for i in range(1,10)]
l1
a = 1
l2 = [a for x in input().strip().split(" ")]
print(l2)
print(type(l2[0]))

1 2 3 4
[1, 1, 1, 1]
<class 'int'>


In [42]:
l2 = input().strip().split(" ")
l3 = [int(x) for x in l2]
print(l3)
print(l3[0])

1 2 3 4
[1, 2, 3, 4]
1


In [44]:
#2D lists

In [51]:
##Modules

import math as m
import numpy as np
import pandas as p
import matplotlib.pyplot as plt

In [49]:
print(m.sqrt(4))

2.0


In [67]:
#Numpy

l1 = [1,2,3,4]
l1 = np.array(l1)

l2 = np.zeros(10)
print(l2)

l3 = np.ones(10)
print(l3)

l4 = np.array([1,2,3])
print(l4)

l5 = np.arange(1,10)
print(l5)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[1 2 3]
[1 2 3 4 5 6 7 8 9]
