In [37]:
import numpy as np
from sklearn import datasets
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn import preprocessing

In [38]:
cancer_ds = datasets.load_breast_cancer()

In [39]:
x = cancer_ds.data
y = cancer_ds.target

In [40]:
df = pd.DataFrame(x)

In [41]:
df.describe()

0           1           2            3           4   \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    14.127292   19.289649   91.969033   654.889104    0.096360   
std      3.524049    4.301036   24.298981   351.914129    0.014064   
min      6.981000    9.710000   43.790000   143.500000    0.052630   
25%     11.700000   16.170000   75.170000   420.300000    0.086370   
50%     13.370000   18.840000   86.240000   551.100000    0.095870   
75%     15.780000   21.800000  104.100000   782.700000    0.105300   
max     28.110000   39.280000  188.500000  2501.000000    0.163400   

               5           6           7           8           9      ...      \
count  569.000000  569.000000  569.000000  569.000000  569.000000     ...       
mean     0.104341    0.088799    0.048919    0.181162    0.062798     ...       
std      0.052813    0.079720    0.038803    0.027414    0.007060     ...       
min      0.019380    0.000000    0.000000    0.106000    0.049960     ...       
25%      0.064920    0.029560    0.020310    0.161900    0.057700     ...       
50%      0.092630    0.061540    0.033500    0.179200    0.061540     ...       
75%      0.130400    0.130700    0.074000    0.195700    0.066120     ...       
max      0.345400    0.426800    0.201200    0.304000    0.097440     ...       

               20          21          22           23          24  \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    16.269190   25.677223  107.261213   880.583128    0.132369   
std      4.833242    6.146258   33.602542   569.356993    0.022832   
min      7.930000   12.020000   50.410000   185.200000    0.071170   
25%     13.010000   21.080000   84.110000   515.300000    0.116600   
50%     14.970000   25.410000   97.660000   686.500000    0.131300   
75%     18.790000   29.720000  125.400000  1084.000000    0.146000   
max     36.040000   49.540000  251.200000  4254.000000    0.222600   

               25          26          27          28          29  
count  569.000000  569.000000  569.000000  569.000000  569.000000  
mean     0.254265    0.272188    0.114606    0.290076    0.083946  
std      0.157336    0.208624    0.065732    0.061867    0.018061  
min      0.027290    0.000000    0.000000    0.156500    0.055040  
25%      0.147200    0.114500    0.064930    0.250400    0.071460  
50%      0.211900    0.226700    0.099930    0.282200    0.080040  
75%      0.339100    0.382900    0.161400    0.317900    0.092080  
max      1.058000    1.252000    0.291000    0.663800    0.207500  

[8 rows x 30 columns]

In [42]:
from sklearn import model_selection
xTrain,xTest,yTrain,yTest = model_selection.train_test_split(x,y,random_state=0)

In [43]:
print(x.shape,xTrain.shape,xTest.shape)

(569, 30) (426, 30) (143, 30)


In [44]:
scalar = preprocessing.StandardScaler()
scalar.fit(xTrain)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [45]:
scalar.transform(xTrain)

array([[-0.65079907, -0.43057322, -0.68024847, ..., -0.36433881,
         0.32349851, -0.7578486 ],
       [-0.82835341,  0.15226547, -0.82773762, ..., -1.45036679,
         0.62563098, -1.03071387],
       [ 1.68277234,  2.18977235,  1.60009756, ...,  0.72504581,
        -0.51329768, -0.96601386],
       ..., 
       [-1.33114223, -0.22172269, -1.3242844 , ..., -0.98806491,
        -0.69995543, -0.12266325],
       [-1.25110186, -0.24600763, -1.28700242, ..., -1.75887319,
        -1.56206114, -1.00989735],
       [-0.74662205,  1.14066273, -0.72203706, ..., -0.2860679 ,
        -1.24094654,  0.2126516 ]])

In [46]:
clf = LogisticRegression()

In [47]:
clf.fit(xTrain,yTrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
scalar.transform(xTest)

array([[-0.21395901,  0.3125461 , -0.14355187, ...,  1.37043754,
         1.08911166,  1.53928319],
       [-0.26750714,  1.461224  , -0.32955207, ..., -0.84266106,
        -0.71577388, -0.88105993],
       [-0.03922298, -0.86770223, -0.10463112, ..., -0.505318  ,
        -1.20298225, -0.92494342],
       ..., 
       [-0.51270124, -1.69096186, -0.54095317, ..., -0.12632201,
         0.33773512, -0.42872244],
       [-0.17732081, -2.01395163, -0.17345939, ..., -0.62875108,
        -0.29500302, -0.65432858],
       [ 1.5305829 , -0.26300709,  1.57961296, ...,  1.6694843 ,
         1.18085869,  0.48889253]])

In [50]:
clf.predict(xTest) - yTest

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, -1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0])

In [51]:
clf.score(xTest,yTest)

0.95804195804195802

In [59]:
df = pd.DataFrame(clf.predict_proba(xTrain))

In [92]:
y_hypo = clf.predict_proba(xTest)

In [75]:
np.set_printoptions(precision=4,suppress=True)

In [93]:
df = pd.DataFrame(y_hypo)

In [94]:
y_hypo.shape

(143, 2)

In [95]:
for j in range(y_hypo.shape[1]):
    for i in range(y_hypo.shape[0]):
        y_hypo[i][j] = "{:.4f}".format(y_hypo[i][j])
    
        

In [96]:
df

0       1
0    0.9932  0.0068
1    0.0306  0.9694
2    0.0024  0.9976
3    0.2060  0.7940
4    0.0001  0.9999
5    0.0032  0.9968
6    0.0074  0.9926
7    0.0018  0.9982
8    0.0412  0.9588
9    0.0002  0.9998
10   0.4363  0.5637
11   0.1652  0.8348
12   0.0042  0.9958
13   0.7836  0.2164
14   0.2314  0.7686
15   0.9921  0.0079
16   0.0159  0.9841
17   1.0000  0.0000
18   0.9985  0.0015
19   1.0000  0.0000
20   1.0000  0.0000
21   0.9117  0.0883
22   0.0018  0.9982
23   0.0123  0.9877
24   0.9925  0.0075
25   0.0119  0.9881
26   0.0023  0.9977
27   0.8021  0.1979
28   0.0036  0.9964
29   1.0000  0.0000
..      ...     ...
113  0.1236  0.8764
114  0.0053  0.9947
115  0.1408  0.8592
116  0.0602  0.9398
117  0.0006  0.9994
118  0.2046  0.7954
119  0.0049  0.9951
120  0.0101  0.9899
121  0.0019  0.9981
122  0.9414  0.0586
123  0.0066  0.9934
124  1.0000  0.0000
125  0.0410  0.9590
126  0.6411  0.3589
127  0.0005  0.9995
128  0.0009  0.9991
129  0.0015  0.9985
130  1.0000  0.0000
131  0.0146  0.9854
132  0.0024  0.9976
133  0.1172  0.8828
134  0.0957  0.9043
135  0.0003  0.9997
136  0.3066  0.6934
137  0.9258  0.0742
138  1.0000  0.0000
139  0.0007  0.9993
140  0.0020  0.9980
141  0.0005  0.9995
142  1.0000  0.0000

[143 rows x 2 columns]

In [97]:
yPre-yTest

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, -1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0])

In [98]:
from sklearn.metrics import confusion_matrix,classification_report

In [101]:
confusion_matrix(yTest,yPre)

array([[52,  1],
       [ 5, 85]])

In [103]:
print(classification_report(yTest,yPre))

             precision    recall  f1-score   support

          0       0.91      0.98      0.95        53
          1       0.99      0.94      0.97        90

avg / total       0.96      0.96      0.96       143



In [104]:
y_hypo.dtype

dtype('float64')