In [1]:
import math as m

print(m.sqrt(10))

3.1622776601683795


In [8]:
import numpy as np
l = [1,2,3]
b = np.array(l)
a = np.array(l,int)
c = np.zeros(10)
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))
print(b.dtype)
print(a.dtype)
print(c.dtype)

[1 2 3]
[1 2 3]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
int64
float64


In [21]:
d = np.zeros((2,3))
print(d)
print(d.shape)
print(type(d))
print(d.dtype)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
(2, 3)
<class 'numpy.ndarray'>
float64


In [15]:
e = np.zeros(10,int)
e[0]=1
print(e)
print(e.dtype)
print(e.shape)

[1 0 0 0 0 0 0 0 0 0]
int64
(10,)
(2, 3)


In [23]:
f = np.arange(10)
print(f)
print(f.dtype)
print(type(f))

[0 1 2 3 4 5 6 7 8 9]
int64
<class 'numpy.ndarray'>


In [41]:
g = np.array(([1,2,3],[4,5,6]))
print(g)
print(g[0])
print(g[0][2])
print(g[:,0])

[[1 2 3]
 [4 5 6]]
[1 2 3]
3
[1 4]


In [53]:
h = np.array([0,1])
i = np.array(([1,2]))
j = m.sqrt(((h-i)**2).sum())
print(j)

x = np.array([1,2,3,4,5,6])
y = ((x-x.mean())**2).sum()


1.4142135623730951
17.5


In [62]:
np.sum([[0,1],[1,5],[2,3]],axis=0)

array([3, 9])

In [38]:
import pandas as pd

iris = pd.read_csv("Iris.csv")
print(type(iris))
data = iris.copy()
#print(data.head())
print(data.shape)
data.head()

<class 'pandas.core.frame.DataFrame'>
(150, 6)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [39]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000