In [2]:
import numpy as np

In [4]:
l1 = [1,2,3]
np.array(l1)

array([1, 2, 3])

In [6]:
#numpy converts all elements to same datatype
l2 = [1,2,"arr"]
np.array(l2)

array(['1', '2', 'arr'], dtype='<U21')

In [8]:
a = np.zeros(10)
print(a.dtype)

a = np.zeros(10, int)
print(a.dtype)

float64
int64


In [10]:
#Creating multi dimensional numpy arrays
b = np.zeros((2,3,2))
print(b.shape)

(2, 3, 2)


In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [23]:
print(a*b)
print(a.dot(b))
print(a.shape)
print(b.shape)
print(a.T)
print(a.T.shape)
print(np.matmul(a,b))

[ 4 10 18]
32
(3,)
(3,)
[1 2 3]
(3,)
32


From the documentation:

matmul differs from dot in two important ways.

Multiplication by scalars is not allowed.
Stacks of matrices are broadcast together as if the matrices were elements.
The last point makes it clear that dot and matmul methods behave differently when passed 3D (or higher dimensional) arrays. Quoting from the documentation some more:

For matmul:

If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.

For np.dot:

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b

In [28]:
#matrix multiplication
c = np.array([[1,3],[1,2],[0,1]])
r = np.array([[1,0,2],[0,1,2]])

print(c.shape)
print(r.shape)
print(np.matmul(c,r))
#print(c*r) -> error, since point-wise operation and dimensions don't match
print(np.dot(c,r))

(3, 2)
(2, 3)
[[1 3 8]
 [1 2 6]
 [0 1 2]]
[[1 3 8]
 [1 2 6]
 [0 1 2]]
